### ISSUE TITLE
Send a Tweet for new Events

### ISSUE THREAD

**Issue by PatrickHeneise** [gitevents/broadcast#4]
This is pretty straight forward; there's an action to dispatch a tweet already, we just need to fetch the right data from the event body before.

```
ame: New Talk Proposal
 on:
   issues:
     types: [labeled]

 jobs:
   tweet:
     runs-on: ubuntu-latest
     steps:
       - uses: ethomson/send-tweet-action@v1
         if: contains(github.event.issue.labels,'proposal')
         with:
           status: "New talk proposal: ${{github.event.issue.title}} ${{github.event.issue.html_url}} #CyprusJS"
           consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
           consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
           access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
           access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} 
```

https://github.com/cyprusjs/CyprusJS/commit/07c746cf6b7b445db9e677022307275270c78072
